networks:
  project-network:
  local-shared-network:
    external: true

services:
  app-service:
    build:
      context: .
      dockerfile: ./php/dockerfile
    container_name: app_container
    # command: ["sh", "-c", "tail -f /dev/null"]
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html/app
      # - ./php/php.ini-production.template:/usr/local/etc/php/php.ini-production
      # - ./php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "9000:9000"
    networks:
      - project-network
      - local-shared-network
  
  nginx-service:
    image: nginx:stable-alpine
    restart: unless-stopped
    container_name: nginx_container
    # command: ["sh", "-c", "tail -f /dev/null"]
    ports:
      - "8181:80"
    volumes:
      - ./app:/var/www/html/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app-service
    networks:
      - project-network

